### ISSUE TITLE
Pluralizer problem

### ISSUE THREAD

**Issue by MohammadSata** [doctrine/inflector#156]
# Laravel Version: 7.11.0
# PHP Version: 7.2.24

Description:
The output of the following code is incorrect
Str::plural('Research')

Output code: Research
The output it has to give: Researches

**Comment by Bouhnosaure** [comment]
Same issue here

The word "Taxon" was pluralized to "Taxons" and now it is pluralized to "Taxa"

**Comment by taiwanleaftea** [comment]
The same problem with "work"
It should be "works", but returns "work"

In previous versions it was pluralized to "works"

**Comment by alcaeus** [comment]
> The word "Taxon" was pluralized to "Taxons" and now it is pluralized to "Taxa"

The plural of "Taxon" is "Taxa", not "Taxons". This was a long-standing bug that was fixed. You can work around this by using custom rules, as explained here: https://github.com/doctrine/inflector/issues/147#issuecomment-628807276.

I'll take another look at the pluralisation rules to figure out why "Research" is not producing the expected result.

**Comment by tomcastleman** [comment]
@alcaeus thanks for your work on this package.

I have an interesting question which must have been raised before although I can't find it:

Should pluralization rules be changed in non-major version upgrades of this package when there are thousands of projects relying on the rules for things like table names and such?

When upgrading the minor version of this package (1.3.x...1.4.x), the DB layer of many dependent apps (ORMs, Migrations etc) will change how various names and identifiers are generated, and therefore may break. In my case due to `weathers` -> `weather`. I don't dispute this is a _fix_ to the correct pluralisation (although there may be some debate about that), but should this then break BC?

[related](https://github.com/laravel/framework/pull/32734#issuecomment-630789949)

**Comment by alcaeus** [comment]
> Should pluralization rules be changed in non-major version upgrades of this package when there are thousands of projects relying on the rules for things like table names and such?

Interesting questions. There are two ways coming into play for 1.4.0. For one, Inflector 2.0 provides a new API underneath that allows us to support multiple languages. To help with the transition to 2.0, we changed the 1.x API to be a layer on top of the new API. This means that you can continue to use the package as expected, but under the hood it's using the new logic. This has created some bugs (e.g. "research" being pluralised to "research" instead of "researches"), and fixed some long-standing bugs (e.g. the above-mentioned "taxon" -> "taxons" pluralisation).

The impact of these changes is hard to judge from our point of view. Doctrine uses this library in its (deprecated) entity generation tools, which are called during the development cycle, not during production use. This removes the danger of a bug fix breaking your app in production.

> Using an inflector for table names and critical parts of your DB layer seems a bit flawed to me if the pluralisation rules are going to change under the hood without a major version upgrade.

I agree, which is why I personally wouldn't recommend doing that, but I don't have the power to influence other projects that way. It's unfortunate that a bug fix in a grammar library has such consequences, but I believe that the idea of automatically generating table names based on notoriously hard to implement grammar rules is a risky choice to begin with.

**Comment by tomcastleman** [comment]
Thanks for your quick reply @alcaeus. I have created a [discussion point](https://github.com/laravel/ideas/issues/2251) for Laravel. Let's see what people have to say over there.

Thanks again.

**Comment by alcaeus** [comment]
I've created #157 to fix pluralisation of "research" and "homework". "Work" is correctly pluralised to "works" as indicated in the tests.

**Comment by beberlei** [comment]
One approach to fix this is that we could introduce a new language rules abstraction that brings bug the old singularize and pluralize rules of the 1.x branch and triggers a deprecation warning. I will look into it this week.

**Comment by alcaeus** [comment]
After further discussion, we won't fix "research" and "homework". Please see discussion in https://github.com/doctrine/inflector/pull/157#issuecomment-630999574 for details.
