### ISSUE TITLE
Pluralize Error

### ISSUE THREAD

**Issue by Kiba86** [doctrine/inflector#161]
Str::pluralStudly('Travel') return "travel" and not "travels"

**Comment by alcaeus** [comment]
Thanks for the issue report. I've created a separate issue to explain why these inflections changed: https://github.com/doctrine/inflector/issues/163. That said, while writing that issue I discovered a bug that made it impossible to override uninflected words (like travel). This will be fixed in the upcoming 1.4.3 and 2.0.3 releases. Both will be released today or tomorrow.
